# Generated by Django 6.0.1 on 2026-01-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='created_at',
            new_name='date_joined',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
